# Generated by Django 6.1.1 on 2026-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preacher', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('bible_verse', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='sermons/videos/')),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
