# Generated by Django 6.1.2 on 2026-10-08 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
