# Generated by Django 6.1.1 on 2026-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message_type', models.CharField(choices=[('prayer', 'Prayer Request'), ('inquiry', 'General Inquiry'), ('spiritual', 'Spiritual Support'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'private message',
                'verbose_name_plural': 'private messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
